config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :users

  validates :title, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :items

  validates :username, presence: true, uniqueness: true
  validates :password, confirmation: true
  validates :password_confirmation, presence:true, length: {in: 6..20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authorize

  def index
    @user = User.find(params[:user_id])
    @items = @user.items.all
  end

  def new
    @item = Item.new
  end

  def create
    user = current_user
    @item = Item.new(item_params)
    user.items.push(@item)

    if @item.save
      redirect_to user_items_path(current_user)
    else
      render "new"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to user_path(current_user)
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.users.delete(current_user)

    if @item.posts.blank?
      @item.destroy
    end

    redirect_to user_path(current_user)
  end

  private

  def item_params
    params.require(:item).permit(
      :title,
      :description,
      :completed,
      :date_completed
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    else
      redirect_to("/")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to("/")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to "/"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete

    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :password,
      :password_confirmation,
      :bio
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, @item] do |f| %>

  <% if @item.errors.any? %>
    <div id="error_message">
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p>
      title: <br><%= f.text_field :title %>
    </p>
    <p>
      description: <br><%= f.text_area :description %>
    </p>
    <p>
      completed: <br><%= f.check_box :completed %>
    </p>
    <p>
      completed date: <br><%= f.date_field :date_completed %>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="form">
  <h1>Edit/Delete Item</h1>

  <%= render "form" %>

  <p><%= link_to "Delete Item", user_item_path(current_user, item),method: :delete, data: {confirm: "Are you sure?"}%></p>

  <p><%= link_to "Back to Your Posts", user_path(current_user) %></p>
</div>

app/views/items/index.html.erb
<a class="#top"></a>
<div class="items">
  <% if @user == current_user %>
  <h1>Your Bucket List</h1>
  <% else %>
  <h1><%= @user.username.titleize %>'s Bucket List</h1>
  <% end %>

  <ul class="items">
    <% @items.order("created_at ASC").each do |item| %>
    <li>
      <h2><%= item.title %></h2>

      <p><%= item.description %></p>
      <p>Finished: <%= item.completed %></p>
      <p>Completed On: <%= item.date_completed %></p>

      <% if item.user_id == current_user.id %>
        <p><%= link_to "edit", edit_user_item_path(current_user, item) %> <%= link_to "delete", user_item_path(current_user, item), method: :delete, data: {confirm: "Are you sure?"}%></p>
      <% end %>
    </li>
    <% end %>
  </ul>

</div>

<a href="#top">Back to the Top</a>

app/views/items/new.html.erb
<div class="form">
  <h1>New Item</h1>

  <%= render "form" %>

  <p>
    <%= link_to "Back Your Items", user_items_path(current_user) %>
  </p>

  <p>
    <%= link_to "Back to Home", users_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketListApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <% if current_user %>
    <ul class="menu">
      <li>Signed in as <%= current_user.username.upcase %></li>
      <li><%= link_to "Home", users_path %></li>
      <li><%= link_to "Your Lists", user_items_path(current_user) %></li>
      <li><%= link_to "Create New Item", new_user_item_path(current_user) %></li>
      <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
      <li><%= link_to "Logout", logout_path %></li>
    </ul>
    <% else %>
      <div>
        <h3>Please Login</h3>
      </div>
    <% end %>
  </nav>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_message">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p>
      <%= f.text_field :username, placeholder: "username" %>
    </p>
    <p>
      <%= f.password_field :password, placeholder: "password" %>
    </p>
    <p>
      <%= f.password_field :password_confirmation, placeholder: "confirm password" %>
    </p>
    <p>
      <%= f.text_area :bio, placeholder: "about you" %><br>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="form">
<h1>EDIT/DELETE ACCOUNT</h1>

<%= render "form" %>

<p>
<%= link_to "Delete Account", user_path(current_user), method: :delete, data: {confirm: "Are you sure?"}%>
</p>
<p>
<%= link_to "Back to Home", users_path %>
</p>
</div>

app/views/users/index.html.erb
<div class="users">
  <h1>Explore Someone Else's Bucket List</h1>
  <% @users.order("username ASC").each do |user| %>
  <h2>
    <a href="<%= user_items_path(user) %>">
      <%= user.username.upcase %>
    </a>
  </h2>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form">
  <h1>Join</h1>
  <%= render "form" %>

  <%= link_to "Back to Login", "/" %>
</div>